#!/usr/bin/expect
set timeout 1
set ip [lindex $argv 0]
set port [lindex $argv 1]
set node_name [lindex $argv 2]
set metric [lindex $argv 3]
set query_date [lindex $argv 4]
spawn telnet $ip $port
expect "'^]'."
send -- "fetch yellowstone/$node_name/GOps.rrd AVERAGE -s \'00:00 $query_date\' -e \'23:59 $query_date\'\r" 
send -- "fetch yellowstone/$node_name/MFLOPs.rrd AVERAGE -s \'00:00 $query_date\' -e \'23:59 $query_date\'\r" 
send -- "fetch yellowstone/$node_name/boottime.rrd AVERAGE -s \'00:00 $query_date\' -e \'23:59 $query_date\'\r" 
send -- "fetch yellowstone/$node_name/bytes_in.rrd AVERAGE -s \'00:00 $query_date\' -e \'23:59 $query_date\'\r" 
send -- "fetch yellowstone/$node_name/bytes_out.rrd AVERAGE -s \'00:00 $query_date\' -e \'23:59 $query_date\'\r" 
send -- "fetch yellowstone/$node_name/cpu_aidle.rrd AVERAGE -s \'00:00 $query_date\' -e \'23:59 $query_date\'\r" 
send -- "fetch yellowstone/$node_name/cpu_idle.rrd AVERAGE -s \'00:00 $query_date\' -e \'23:59 $query_date\'\r" 
send -- "fetch yellowstone/$node_name/cpu_nice.rrd AVERAGE -s \'00:00 $query_date\' -e \'23:59 $query_date\'\r" 
send -- "fetch yellowstone/$node_name/cpu_num.rrd AVERAGE -s \'00:00 $query_date\' -e \'23:59 $query_date\'\r" 
send -- "fetch yellowstone/$node_name/cpu_speed.rrd AVERAGE -s \'00:00 $query_date\' -e \'23:59 $query_date\'\r" 
send -- "fetch yellowstone/$node_name/cpu_system.rrd AVERAGE -s \'00:00 $query_date\' -e \'23:59 $query_date\'\r" 
send -- "fetch yellowstone/$node_name/cpu_user.rrd AVERAGE -s \'00:00 $query_date\' -e \'23:59 $query_date\'\r" 
send -- "fetch yellowstone/$node_name/cpu_wio.rrd AVERAGE -s \'00:00 $query_date\' -e \'23:59 $query_date\'\r" 
send -- "fetch yellowstone/$node_name/disk_free.rrd AVERAGE -s \'00:00 $query_date\' -e \'23:59 $query_date\'\r" 
send -- "fetch yellowstone/$node_name/disk_total.rrd AVERAGE -s \'00:00 $query_date\' -e \'23:59 $query_date\'\r" 
send -- "fetch yellowstone/$node_name/entropy_avail.rrd AVERAGE -s \'00:00 $query_date\' -e \'23:59 $query_date\'\r" 
send -- "fetch yellowstone/$node_name/load_fifteen.rrd AVERAGE -s \'00:00 $query_date\' -e \'23:59 $query_date\'\r" 
send -- "fetch yellowstone/$node_name/load_five.rrd AVERAGE -s \'00:00 $query_date\' -e \'23:59 $query_date\'\r" 
send -- "fetch yellowstone/$node_name/load_one.rrd AVERAGE -s \'00:00 $query_date\' -e \'23:59 $query_date\'\r" 
send -- "fetch yellowstone/$node_name/mem_buffers.rrd AVERAGE -s \'00:00 $query_date\' -e \'23:59 $query_date\'\r" 
send -- "fetch yellowstone/$node_name/mem_cached.rrd AVERAGE -s \'00:00 $query_date\' -e \'23:59 $query_date\'\r" 
send -- "fetch yellowstone/$node_name/mem_free.rrd AVERAGE -s \'00:00 $query_date\' -e \'23:59 $query_date\'\r" 
send -- "fetch yellowstone/$node_name/mem_shared.rrd AVERAGE -s \'00:00 $query_date\' -e \'23:59 $query_date\'\r" 
send -- "fetch yellowstone/$node_name/mem_total.rrd AVERAGE -s \'00:00 $query_date\' -e \'23:59 $query_date\'\r" 
send -- "fetch yellowstone/$node_name/part_max_used.rrd AVERAGE -s \'00:00 $query_date\' -e \'23:59 $query_date\'\r" 
send -- "fetch yellowstone/$node_name/pkts_in.rrd AVERAGE -s \'00:00 $query_date\' -e \'23:59 $query_date\'\r" 
send -- "fetch yellowstone/$node_name/pkts_out.rrd AVERAGE -s \'00:00 $query_date\' -e \'23:59 $query_date\'\r" 
send -- "fetch yellowstone/$node_name/proc_run.rrd AVERAGE -s \'00:00 $query_date\' -e \'23:59 $query_date\'\r" 

expect eof
