#!/usr/bin/expect
set timeout 1
set ip [lindex $argv 0]
set port [lindex $argv 1]
set rack_name_0 [lindex $argv 2] 
set rack_name_1 [lindex $argv 3] 
set rack_name_2 [lindex $argv 4] 
set node_name [lindex $argv 5]
set metric [lindex $argv 6]
set query_date [lindex $argv 7]
spawn telnet $ip $port
expect "'^]'."

send -- "fetch $rack_name_0\" \"$rack_name_1\" \"$rack_name_2/$node_name/$metric.rrd AVERAGE -s \'00:00 $query_date\' -e \'23:59 $query_date\'\r" 
expect eof
