#!/usr/bin/expect
set timeout 1
set ip [lindex $argv 0]
set port [lindex $argv 1]
set node_name [lindex $argv 2]
set metric [lindex $argv 3]
set query_date [lindex $argv 4]
spawn telnet $ip $port
expect "'^]'."
send -- "xport -s \'00:00 $query_date\' -e \'23:59 $query_date\' DEF:out=yellowstone/$node_name/$metric.rrd:sum:AVERAGE XPORT:out:\'$metric\'\r" 
expect eof
