#!/usr/bin/expect
set timeout 1
set machine [lindex $argv 0]
set port [lindex $argv 1]
set node_name [lindex $argv 2]
set metric [lindex $argv 3]
set query_date [lindex $argv 4]
spawn telnet ganglia $port
expect "'^]'."
send -- "cd yellowstone \r"
expect "'^]'."
send -- "fetch $node_name/cpu_intr.rrd AVERAGE -s \'00:00 $query_date\' -e \'23:59 $query_date\'\r" 
send -- "fetch $node_name/mem_cached.rrd AVERAGE -s \'00:00 $query_date\' -e \'23:59 $query_date\'\r" 
send -- "fetch $node_name/disk_free.rrd AVERAGE -s \'00:00 $query_date\' -e \'23:59 $query_date\'\r" 
send -- "fetch $node_name/ib0_rcv_data.rrd AVERAGE -s \'00:00 $query_date\' -e \'23:59 $query_date\'\r" 
send -- "fetch $node_name/hpm_snl_rate_usertime.rrd AVERAGE -s \'00:00 $query_date\' -e \'23:59 $query_date\'\r" 
send -- "fetch $node_name/swap_free.rrd AVERAGE -s \'00:00 $query_date\' -e \'23:59 $query_date\'\r" 
send -- "fetch $node_name/hpm_wallclock.rrd AVERAGE -s \'00:00 $query_date\' -e \'23:59 $query_date\'\r" 
send -- "fetch $node_name/load_one.rrd AVERAGE -s \'00:00 $query_date\' -e \'23:59 $query_date\'\r" 
expect eof
send -- "fetch $node_name/cpu_speed.rrd AVERAGE -s \'00:00 $query_date\' -e \'23:59 $query_date\'\r" 
send -- "fetch $node_name/ib0_xmit_data.rrd AVERAGE -s \'00:00 $query_date\' -e \'23:59 $query_date\'\r" 
send -- "fetch $node_name/part_max_used.rrd AVERAGE -s \'00:00 $query_date\' -e \'23:59 $query_date\'\r" 
send -- "fetch $node_name/bytes_out.rrd AVERAGE -s \'00:00 $query_date\' -e \'23:59 $query_date\'\r" 
send -- "fetch $node_name/hpm_dbl_packed_flops.rrd AVERAGE -s \'00:00 $query_date\' -e \'23:59 $query_date\'\r" 
send -- "fetch $node_name/disk_total.rrd AVERAGE -s \'00:00 $query_date\' -e \'23:59 $query_date\'\r" 
send -- "fetch $node_name/hpm_dbl_scalar_flops.rrd AVERAGE -s \'00:00 $query_date\' -e \'23:59 $query_date\'\r" 
send -- "fetch $node_name/proc_run.rrd AVERAGE -s \'00:00 $query_date\' -e \'23:59 $query_date\'\r" 
expect eof
send -- "fetch $node_name/pkts_out.rrd AVERAGE -s \'00:00 $query_date\' -e \'23:59 $query_date\'\r" 
send -- "fetch $node_name/mem_free.rrd AVERAGE -s \'00:00 $query_date\' -e \'23:59 $query_date\'\r" 
send -- "fetch $node_name/hpm_snl_rate_wallclock.rrd AVERAGE -s \'00:00 $query_date\' -e \'23:59 $query_date\'\r" 
send -- "fetch $node_name/mem_shared.rrd AVERAGE -s \'00:00 $query_date\' -e \'23:59 $query_date\'\r" 
send -- "fetch $node_name/cpu_system.rrd AVERAGE -s \'00:00 $query_date\' -e \'23:59 $query_date\'\r" 
send -- "fetch $node_name/cpu_nice.rrd AVERAGE -s \'00:00 $query_date\' -e \'23:59 $query_date\'\r" 
send -- "fetch $node_name/hpm_flops.rrd AVERAGE -s \'00:00 $query_date\' -e \'23:59 $query_date\'\r" 
send -- "fetch $node_name/hpm_dbl_rate_usertime.rrd AVERAGE -s \'00:00 $query_date\' -e \'23:59 $query_date\'\r" 
expect eof
send -- "fetch $node_name/boottime.rrd AVERAGE -s \'00:00 $query_date\' -e \'23:59 $query_date\'\r" 
send -- "fetch $node_name/bytes_in.rrd AVERAGE -s \'00:00 $query_date\' -e \'23:59 $query_date\'\r" 
send -- "fetch $node_name/hpm_snl_packed.rrd AVERAGE -s \'00:00 $query_date\' -e \'23:59 $query_date\'\r" 
send -- "fetch $node_name/pkts_in.rrd AVERAGE -s \'00:00 $query_date\' -e \'23:59 $query_date\'\r" 
send -- "fetch $node_name/load_five.rrd AVERAGE -s \'00:00 $query_date\' -e \'23:59 $query_date\'\r" 
send -- "fetch $node_name/cpu_aidle.rrd AVERAGE -s \'00:00 $query_date\' -e \'23:59 $query_date\'\r" 
send -- "fetch $node_name/cpu_user.rrd AVERAGE -s \'00:00 $query_date\' -e \'23:59 $query_date\'\r" 
send -- "fetch $node_name/hpm_dbl_rate_wallclock.rrd AVERAGE -s \'00:00 $query_date\' -e \'23:59 $query_date\'\r" 
expect eof
send -- "fetch $node_name/mem_buffers.rrd AVERAGE -s \'00:00 $query_date\' -e \'23:59 $query_date\'\r" 
send -- "fetch $node_name/cpu_sintr.rrd AVERAGE -s \'00:00 $query_date\' -e \'23:59 $query_date\'\r" 
send -- "fetch $node_name/cpu_idle.rrd AVERAGE -s \'00:00 $query_date\' -e \'23:59 $query_date\'\r" 
send -- "fetch $node_name/cpu_num.rrd AVERAGE -s \'00:00 $query_date\' -e \'23:59 $query_date\'\r" 
send -- "fetch $node_name/swap_total.rrd AVERAGE -s \'00:00 $query_date\' -e \'23:59 $query_date\'\r" 
send -- "fetch $node_name/mem_total.rrd AVERAGE -s \'00:00 $query_date\' -e \'23:59 $query_date\'\r" 
send -- "fetch $node_name/hpm_snl_scalar.rrd AVERAGE -s \'00:00 $query_date\' -e \'23:59 $query_date\'\r" 
send -- "fetch $node_name/load_fifteen.rrd AVERAGE -s \'00:00 $query_date\' -e \'23:59 $query_date\'\r" 
expect eof
send -- "fetch $node_name/cpu_wio.rrd AVERAGE -s \'00:00 $query_date\' -e \'23:59 $query_date\'\r" 
send -- "fetch $node_name/proc_total.rrd AVERAGE -s \'00:00 $query_date\' -e \'23:59 $query_date\'\r" 

expect eof
